"""Regression test generated by transcript-to-test."""
import json


TOOL_REGISTRY = {('lookup_capital', '{"country":"France"}'): 'Paris', ('lookup_population', '{"city":"Paris"}'): '2102650'}


EXPECTED_TURNS = [ { 'content': None,
    'model': None,
    'provider': 'openai',
    'role': 'assistant',
    'tool_calls': [ { 'function': {'arguments': '{"country":"France"}', 'name': 'lookup_capital'},
                      'id': 'call_capital',
                      'type': 'function'}],
    'tool_results': None,
    'ts': '2026-07-22T00:00:00+00:00'},
  { 'content': [{'content': 'Paris', 'tool_use_id': 'call_capital', 'type': 'tool_result'}],
    'model': None,
    'provider': 'openai',
    'role': 'tool',
    'tool_calls': None,
    'tool_results': [{'content': 'Paris', 'tool_use_id': 'call_capital'}],
    'ts': '2026-07-22T00:00:00+00:00'},
  { 'content': None,
    'model': None,
    'provider': 'openai',
    'role': 'assistant',
    'tool_calls': [ { 'function': {'arguments': '{"city":"Paris"}', 'name': 'lookup_population'},
                      'id': 'call_population',
                      'type': 'function'}],
    'tool_results': None,
    'ts': '2026-07-22T00:00:00+00:00'},
  { 'content': [{'content': '2102650', 'tool_use_id': 'call_population', 'type': 'tool_result'}],
    'model': None,
    'provider': 'openai',
    'role': 'tool',
    'tool_calls': None,
    'tool_results': [{'content': '2102650', 'tool_use_id': 'call_population'}],
    'ts': '2026-07-22T00:00:00+00:00'},
  { 'content': 'The capital of France is Paris, with a population of 2102650.',
    'model': None,
    'provider': 'openai',
    'role': 'assistant',
    'tool_calls': None,
    'tool_results': None,
    'ts': '2026-07-22T00:00:00+00:00'}]


EXPECTED_FINAL = 'The capital of France is Paris, with a population of 2102650.'


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(
            item.get("text", "")
            for item in content
            if isinstance(item, dict) and item.get("type") == "text"
        )
    return str(content) if content is not None else ""


def _assistant_message(turn):
    msg = {"role": "assistant", "content": _text_of(turn.get("content"))}
    if turn.get("tool_calls"):
        msg["tool_calls"] = turn["tool_calls"]
    return msg


def run_agent(messages, tool_registry, expected_turns):
    i = 0
    while i < len(expected_turns):
        turn = expected_turns[i]
        if turn["role"] != "assistant":
            i += 1
            continue
        messages.append(_assistant_message(turn))
        tool_calls = turn.get("tool_calls") or []
        for tc in tool_calls:
            i += 1
            tool_turn = expected_turns[i]
            assert tool_turn["role"] == "tool"
            expected_result = tool_turn["tool_results"][0]["content"]

            name = tc["function"]["name"]
            args = json.loads(tc["function"]["arguments"])
            key = (name, json.dumps(args, sort_keys=True, separators=(",", ":")))
            actual_result = tool_registry[key]

            assert actual_result == expected_result, (
                f"Tool {name}({args!r}) returned {actual_result!r}, "
                f"expected recorded result {expected_result!r}"
            )
            messages.append({"role": "tool", "tool_call_id": tc["id"], "content": actual_result})

        if not tool_calls:
            return _text_of(turn.get("content"))
        i += 1
    raise RuntimeError("no final assistant turn found in expected_turns")


def test_test_session():
    messages = [{"role": "user", "content": 'What is the capital of France and its population?'}]
    final = run_agent(messages, TOOL_REGISTRY, EXPECTED_TURNS)
    assert final == EXPECTED_FINAL
