"""Render a standalone regression test from canonical turns."""
import json
import pprint
import re


def extract_tool_registry(turns):
    """Build a stub registry from paired assistant tool_calls and tool turns."""
    registry = {}
    i = 0
    while i < len(turns):
        turn = turns[i]
        if turn["role"] == "assistant" and turn.get("tool_calls"):
            for tc in turn["tool_calls"]:
                i += 1
                tool_turn = turns[i]
                assert tool_turn["role"] == "tool"
                name = tc["function"]["name"]
                args = json.loads(tc["function"]["arguments"])
                key = (name, json.dumps(args, sort_keys=True, separators=(",", ":")))
                registry[key] = tool_turn["tool_results"][0]["content"]
        i += 1
    return registry


def filter_assistant_tool_turns(turns):
    """Return only assistant and tool turns, in original order."""
    return [t for t in turns if t["role"] in ("assistant", "tool")]


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts = [item.get("text", "") for item in content
                 if isinstance(item, dict) and item.get("type") == "text"]
        return "".join(texts)
    return str(content) if content is not None else ""


def final_answer(turns):
    """Return the text of the last assistant turn with no tool_calls."""
    for turn in reversed(turns):
        if turn["role"] == "assistant" and not turn.get("tool_calls"):
            return _text_of(turn.get("content"))
    return None


def initial_prompt(turns):
    """Return the first user turn's content as a plain string."""
    for turn in turns:
        if turn["role"] == "user":
            return _text_of(turn.get("content"))
    return ""


def scrub_value(value, scrub_regex):
    """Apply regex substitution to a string value. Non-strings pass through."""
    if scrub_regex is None or not isinstance(value, str):
        return value
    return re.sub(scrub_regex, "", value)


def apply_scrub(turns, scrub_regex):
    """Return a copy of turns with scrubbed tool results and final answer."""
    if scrub_regex is None:
        return turns
    out = []
    for turn in turns:
        t = dict(turn)
        if t["role"] == "tool" and t.get("tool_results"):
            t["tool_results"] = [dict(r) for r in t["tool_results"]]
            for r in t["tool_results"]:
                r["content"] = scrub_value(r["content"], scrub_regex)
            t["content"] = [{"type": "tool_result",
                             "tool_use_id": t["content"][0].get("tool_use_id"),
                             "content": t["tool_results"][0]["content"]}]
        elif t["role"] == "assistant" and not t.get("tool_calls"):
            content = t.get("content")
            if isinstance(content, str):
                t["content"] = scrub_value(content, scrub_regex)
            elif isinstance(content, list):
                t["content"] = [dict(b) for b in content]
                for b in t["content"]:
                    if b.get("type") == "text":
                        b["text"] = scrub_value(b.get("text"), scrub_regex)
        out.append(t)
    return out


_PYTEST_TEMPLATE = '''\
"""Regression test generated by transcript-to-test."""
import json


TOOL_REGISTRY = {tool_registry}


EXPECTED_TURNS = {expected_turns}


EXPECTED_FINAL = {expected_final}


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(
            item.get("text", "")
            for item in content
            if isinstance(item, dict) and item.get("type") == "text"
        )
    return str(content) if content is not None else ""


def _assistant_message(turn):
    msg = {{"role": "assistant", "content": _text_of(turn.get("content"))}}
    if turn.get("tool_calls"):
        msg["tool_calls"] = turn["tool_calls"]
    return msg


def run_agent(messages, tool_registry, expected_turns):
    i = 0
    while i < len(expected_turns):
        turn = expected_turns[i]
        if turn["role"] != "assistant":
            i += 1
            continue
        messages.append(_assistant_message(turn))
        tool_calls = turn.get("tool_calls") or []
        for tc in tool_calls:
            i += 1
            tool_turn = expected_turns[i]
            assert tool_turn["role"] == "tool"
            expected_result = tool_turn["tool_results"][0]["content"]

            name = tc["function"]["name"]
            args = json.loads(tc["function"]["arguments"])
            key = (name, json.dumps(args, sort_keys=True, separators=(",", ":")))
            actual_result = tool_registry[key]

            assert actual_result == expected_result, (
                f"Tool {{name}}({{args!r}}) returned {{actual_result!r}}, "
                f"expected recorded result {{expected_result!r}}"
            )
            messages.append({{"role": "tool", "tool_call_id": tc["id"], "content": actual_result}})

        if not tool_calls:
            return _text_of(turn.get("content"))
        i += 1
    raise RuntimeError("no final assistant turn found in expected_turns")


def test_{name}():
    messages = [{{"role": "user", "content": {initial_prompt}}}]
    final = run_agent(messages, TOOL_REGISTRY, EXPECTED_TURNS)
    {assertion}
'''


_UNITTEST_TEMPLATE = '''\
"""Regression test generated by transcript-to-test."""
import json
import unittest


TOOL_REGISTRY = {tool_registry}


EXPECTED_TURNS = {expected_turns}


EXPECTED_FINAL = {expected_final}


def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(
            item.get("text", "")
            for item in content
            if isinstance(item, dict) and item.get("type") == "text"
        )
    return str(content) if content is not None else ""


def _assistant_message(turn):
    msg = {{"role": "assistant", "content": _text_of(turn.get("content"))}}
    if turn.get("tool_calls"):
        msg["tool_calls"] = turn["tool_calls"]
    return msg


def run_agent(messages, tool_registry, expected_turns):
    i = 0
    while i < len(expected_turns):
        turn = expected_turns[i]
        if turn["role"] != "assistant":
            i += 1
            continue
        messages.append(_assistant_message(turn))
        tool_calls = turn.get("tool_calls") or []
        for tc in tool_calls:
            i += 1
            tool_turn = expected_turns[i]
            assert tool_turn["role"] == "tool"
            expected_result = tool_turn["tool_results"][0]["content"]

            name = tc["function"]["name"]
            args = json.loads(tc["function"]["arguments"])
            key = (name, json.dumps(args, sort_keys=True, separators=(",", ":")))
            actual_result = tool_registry[key]

            assert actual_result == expected_result, (
                f"Tool {{name}}({{args!r}}) returned {{actual_result!r}}, "
                f"expected recorded result {{expected_result!r}}"
            )
            messages.append({{"role": "tool", "tool_call_id": tc["id"], "content": actual_result}})

        if not tool_calls:
            return _text_of(turn.get("content"))
        i += 1
    raise RuntimeError("no final assistant turn found in expected_turns")


class Test{name}(unittest.TestCase):
    def test_run(self):
        messages = [{{"role": "user", "content": {initial_prompt}}}]
        final = run_agent(messages, TOOL_REGISTRY, EXPECTED_TURNS)
        {assertion}


if __name__ == "__main__":
    unittest.main()
'''


def _format_assertion(mode, expected_final, pattern=None):
    if mode == "contains":
        return "assert EXPECTED_FINAL in final"
    if mode == "regex":
        return f"import re\n    assert re.search({pattern!r}, final), f\"final answer {{final!r}} does not match {pattern!r}\""
    return "assert final == EXPECTED_FINAL"


def _format_assertion_unittest(mode, expected_final, pattern=None):
    if mode == "contains":
        return "self.assertIn(EXPECTED_FINAL, final)"
    if mode == "regex":
        return (f"import re\n        self.assertIsNotNone("
                f"re.search({pattern!r}, final), "
                f"f\"final answer {{final!r}} does not match {pattern!r}\")")
    return "self.assertEqual(final, EXPECTED_FINAL)"


def _safe_name(name):
    return re.sub(r"[^0-9a-zA-Z_]", "_", name).strip("_") or "regression"


def render(name, turns, *, assert_mode="exact", framework="pytest", pattern=None):
    """Return the source text of a standalone regression test."""
    expected_turns = filter_assistant_tool_turns(turns)
    tool_registry = extract_tool_registry(expected_turns)
    prompt = initial_prompt(turns) or ""
    expected = final_answer(expected_turns)

    if assert_mode not in ("exact", "contains", "regex"):
        raise ValueError(f"unknown assert mode: {assert_mode}")
    if assert_mode == "regex" and not pattern:
        raise ValueError("--assert regex requires a PATTERN argument")

    fmt = pprint.pformat
    tool_registry_src = fmt(tool_registry, indent=2, width=120)
    expected_turns_src = fmt(expected_turns, indent=2, width=120)

    template = _PYTEST_TEMPLATE if framework == "pytest" else _UNITTEST_TEMPLATE
    if framework == "pytest":
        assertion = _format_assertion(assert_mode, expected, pattern)
    else:
        assertion = _format_assertion_unittest(assert_mode, expected, pattern)

    return template.format(
        name=_safe_name(name),
        tool_registry=tool_registry_src,
        expected_turns=expected_turns_src,
        expected_final=repr(expected),
        initial_prompt=repr(prompt),
        assertion=assertion,
    )
